//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JPSoftworks.QrCodesExtension.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JPSoftworks.QrCodesExtension.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create QR code.
        /// </summary>
        internal static string CodeCreator_Create_ActionTitle {
            get {
                return ResourceManager.GetString("CodeCreator_Create_ActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High (30 %).
        /// </summary>
        internal static string CodeCreator_ErrorCorrection_Choice_High {
            get {
                return ResourceManager.GetString("CodeCreator_ErrorCorrection_Choice_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low (7 %).
        /// </summary>
        internal static string CodeCreator_ErrorCorrection_Choice_Low {
            get {
                return ResourceManager.GetString("CodeCreator_ErrorCorrection_Choice_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium (15 %).
        /// </summary>
        internal static string CodeCreator_ErrorCorrection_Choice_Medium {
            get {
                return ResourceManager.GetString("CodeCreator_ErrorCorrection_Choice_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartile (25 %).
        /// </summary>
        internal static string CodeCreator_ErrorCorrection_Choice_Quartile {
            get {
                return ResourceManager.GetString("CodeCreator_ErrorCorrection_Choice_Quartile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error correction level.
        /// </summary>
        internal static string CodeCreator_ErrorCorrection_Label {
            get {
                return ResourceManager.GetString("CodeCreator_ErrorCorrection_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select error correction level.
        /// </summary>
        internal static string CodeCreator_ErrorCorrection_Placeholder {
            get {
                return ResourceManager.GetString("CodeCreator_ErrorCorrection_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text to encode.
        /// </summary>
        internal static string CodeCreator_Input_Label {
            get {
                return ResourceManager.GetString("CodeCreator_Input_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to encode in QR code.
        /// </summary>
        internal static string CodeCreator_Input_Placeholder {
            get {
                return ResourceManager.GetString("CodeCreator_Input_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module size.
        /// </summary>
        internal static string CodeCreator_ModuleSize_Label {
            get {
                return ResourceManager.GetString("CodeCreator_ModuleSize_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating QR code....
        /// </summary>
        internal static string CodeCreator_Status_Creating {
            get {
                return ResourceManager.GetString("CodeCreator_Status_Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new QR code.
        /// </summary>
        internal static string CodeCreatorPage_Name {
            get {
                return ResourceManager.GetString("CodeCreatorPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create QR code.
        /// </summary>
        internal static string CodeCreatorPage_Title {
            get {
                return ResourceManager.GetString("CodeCreatorPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy QR code.
        /// </summary>
        internal static string CodeListItem_Command_CopyBitmap {
            get {
                return ResourceManager.GetString("CodeListItem_Command_CopyBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy QR code value.
        /// </summary>
        internal static string CodeListItem_Command_CopyValue {
            get {
                return ResourceManager.GetString("CodeListItem_Command_CopyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string CodeListItem_Command_Delete {
            get {
                return ResourceManager.GetString("CodeListItem_Command_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string CodeListItem_Command_Preview {
            get {
                return ResourceManager.GetString("CodeListItem_Command_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating QR code: {0}.
        /// </summary>
        internal static string CodeListItem_Error_Generating_Format {
            get {
                return ResourceManager.GetString("CodeListItem_Error_Generating_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating....
        /// </summary>
        internal static string CodeListItem_Generating {
            get {
                return ResourceManager.GetString("CodeListItem_Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        internal static string CodeListItem_Metadata_CreatedAt {
            get {
                return ResourceManager.GetString("CodeListItem_Metadata_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error correction.
        /// </summary>
        internal static string CodeListItem_Metadata_ErrorCorrection {
            get {
                return ResourceManager.GetString("CodeListItem_Metadata_ErrorCorrection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module size.
        /// </summary>
        internal static string CodeListItem_Metadata_ModuleSize {
            get {
                return ResourceManager.GetString("CodeListItem_Metadata_ModuleSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string CodeListItem_Metadata_Type {
            get {
                return ResourceManager.GetString("CodeListItem_Metadata_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard content.
        /// </summary>
        internal static string CodesIndexPage_ClipboardPreview_DetailsTitle {
            get {
                return ResourceManager.GetString("CodesIndexPage_ClipboardPreview_DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard is empty.
        /// </summary>
        internal static string CodesIndexPage_ClipboardPreview_Empty {
            get {
                return ResourceManager.GetString("CodesIndexPage_ClipboardPreview_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a new QR code from the text content of the clipboard.
        /// </summary>
        internal static string CodesIndexPage_ClipboardPreview_Subtitle {
            get {
                return ResourceManager.GetString("CodesIndexPage_ClipboardPreview_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create QR code from text in clipboard.
        /// </summary>
        internal static string CodesIndexPage_ClipboardPreview_Title {
            get {
                return ResourceManager.GetString("CodesIndexPage_ClipboardPreview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a new QR code from an image stored in the clipboard.
        /// </summary>
        internal static string CodesIndexPage_FromClipboardImage_Subtitle {
            get {
                return ResourceManager.GetString("CodesIndexPage_FromClipboardImage_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create QR code from image in clipboard.
        /// </summary>
        internal static string CodesIndexPage_FromClipboardImage_Title {
            get {
                return ResourceManager.GetString("CodesIndexPage_FromClipboardImage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan all screens for a QR code and add it if one is found.
        /// </summary>
        internal static string CodesIndexPage_FromScreen_Subtitle {
            get {
                return ResourceManager.GetString("CodesIndexPage_FromScreen_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find QR code on screen.
        /// </summary>
        internal static string CodesIndexPage_FromScreen_Title {
            get {
                return ResourceManager.GetString("CodesIndexPage_FromScreen_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a new QR code with default settings from the specified input.
        /// </summary>
        internal static string CodesIndexPage_Instant_Subtitle_Default {
            get {
                return ResourceManager.GetString("CodesIndexPage_Instant_Subtitle_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant QR code from &quot;{0}&quot;.
        /// </summary>
        internal static string CodesIndexPage_Instant_Subtitle_WithInput {
            get {
                return ResourceManager.GetString("CodesIndexPage_Instant_Subtitle_WithInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create QR code instantly.
        /// </summary>
        internal static string CodesIndexPage_Instant_Title {
            get {
                return ResourceManager.GetString("CodesIndexPage_Instant_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string CodesIndexPage_Name {
            get {
                return ResourceManager.GetString("CodesIndexPage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new QR code from specified input.
        /// </summary>
        internal static string CodesIndexPage_NewCode_Subtitle_Default {
            get {
                return ResourceManager.GetString("CodesIndexPage_NewCode_Subtitle_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new QR code.
        /// </summary>
        internal static string CodesIndexPage_NewCode_Subtitle_NoInput {
            get {
                return ResourceManager.GetString("CodesIndexPage_NewCode_Subtitle_NoInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new QR code from &quot;{0}&quot;.
        /// </summary>
        internal static string CodesIndexPage_NewCode_Subtitle_WithInput {
            get {
                return ResourceManager.GetString("CodesIndexPage_NewCode_Subtitle_WithInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search QR codes or type text of a new QR code.
        /// </summary>
        internal static string CodesIndexPage_Placeholder {
            get {
                return ResourceManager.GetString("CodesIndexPage_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR codes.
        /// </summary>
        internal static string CodesIndexPage_Title {
            get {
                return ResourceManager.GetString("CodesIndexPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy QR code to clipboard.
        /// </summary>
        internal static string Commands_CopyBitmapToClipboard_Failure {
            get {
                return ResourceManager.GetString("Commands_CopyBitmapToClipboard_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string Commands_CopyBitmapToClipboard_Name {
            get {
                return ResourceManager.GetString("Commands_CopyBitmapToClipboard_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied QR code image to clipboard.
        /// </summary>
        internal static string Commands_CopyBitmapToClipboard_Success {
            get {
                return ResourceManager.GetString("Commands_CopyBitmapToClipboard_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code not found.
        /// </summary>
        internal static string Commands_GetFromBitmapQrCode_NotFound {
            get {
                return ResourceManager.GetString("Commands_GetFromBitmapQrCode_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code detected and added..
        /// </summary>
        internal static string Commands_GetFromBitmapQrCode_Success {
            get {
                return ResourceManager.GetString("Commands_GetFromBitmapQrCode_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code not found in clipboard image.
        /// </summary>
        internal static string Commands_GetFromClipboardQrCode_NotFound {
            get {
                return ResourceManager.GetString("Commands_GetFromClipboardQrCode_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create QR code: {0}.
        /// </summary>
        internal static string Commands_InstantQrCode_Failure_Format {
            get {
                return ResourceManager.GetString("Commands_InstantQrCode_Failure_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create instant QR code.
        /// </summary>
        internal static string Commands_InstantQrCode_Name {
            get {
                return ResourceManager.GetString("Commands_InstantQrCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code created successfully.
        /// </summary>
        internal static string Commands_InstantQrCode_Success {
            get {
                return ResourceManager.GetString("Commands_InstantQrCode_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview QR code.
        /// </summary>
        internal static string Commands_PreviewQrCode_Name {
            get {
                return ResourceManager.GetString("Commands_PreviewQrCode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code image not found.
        /// </summary>
        internal static string Commands_PreviewQrCode_NotFound {
            get {
                return ResourceManager.GetString("Commands_PreviewQrCode_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (Medium, 15%).
        /// </summary>
        internal static string Settings_InstantQrCode_Ecc_Choice_Default {
            get {
                return ResourceManager.GetString("Settings_InstantQrCode_Ecc_Choice_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default error correction level used when creating instant QR codes..
        /// </summary>
        internal static string Settings_InstantQrCode_Ecc_Description {
            get {
                return ResourceManager.GetString("Settings_InstantQrCode_Ecc_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant QR code: default error correction.
        /// </summary>
        internal static string Settings_InstantQrCode_Ecc_Label {
            get {
                return ResourceManager.GetString("Settings_InstantQrCode_Ecc_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default size (in pixels) of a single QR code module..
        /// </summary>
        internal static string Settings_InstantQrCode_ElementSize_Description {
            get {
                return ResourceManager.GetString("Settings_InstantQrCode_ElementSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant QR code: default module size.
        /// </summary>
        internal static string Settings_InstantQrCode_ElementSize_Label {
            get {
                return ResourceManager.GetString("Settings_InstantQrCode_ElementSize_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display semantic icons instead of generated QR code thumbnails..
        /// </summary>
        internal static string Settings_ShowIcons_Description {
            get {
                return ResourceManager.GetString("Settings_ShowIcons_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show icons instead of QR code thumbnails in the list.
        /// </summary>
        internal static string Settings_ShowIcons_Label {
            get {
                return ResourceManager.GetString("Settings_ShowIcons_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.....
        /// </summary>
        internal static string WorkingForm_Label {
            get {
                return ResourceManager.GetString("WorkingForm_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        internal static string WorkingForm_Text {
            get {
                return ResourceManager.GetString("WorkingForm_Text", resourceCulture);
            }
        }
    }
}
